// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Raft.proto

// Protobuf Java Version: 3.25.3
package io.tinykv.proto.raft;

public interface AppendEntriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tinykv.AppendEntriesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 from_id = 1;</code>
   * @return The fromId.
   */
  int getFromId();

  /**
   * <code>int32 to_id = 2;</code>
   * @return The toId.
   */
  int getToId();

  /**
   * <code>int64 term = 3;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <code>int64 prev_log_index = 4;</code>
   * @return The prevLogIndex.
   */
  long getPrevLogIndex();

  /**
   * <code>int64 prev_log_term = 5;</code>
   * @return The prevLogTerm.
   */
  long getPrevLogTerm();

  /**
   * <code>repeated .tinykv.LogEntry entries = 6;</code>
   */
  java.util.List<io.tinykv.proto.raft.LogEntry> 
      getEntriesList();
  /**
   * <code>repeated .tinykv.LogEntry entries = 6;</code>
   */
  io.tinykv.proto.raft.LogEntry getEntries(int index);
  /**
   * <code>repeated .tinykv.LogEntry entries = 6;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .tinykv.LogEntry entries = 6;</code>
   */
  java.util.List<? extends io.tinykv.proto.raft.LogEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .tinykv.LogEntry entries = 6;</code>
   */
  io.tinykv.proto.raft.LogEntryOrBuilder getEntriesOrBuilder(
      int index);

  /**
   * <code>int64 leader_commit = 7;</code>
   * @return The leaderCommit.
   */
  long getLeaderCommit();
}
