// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Raft.proto

// Protobuf Java Version: 3.25.3
package io.tinykv.proto.raft;

public interface AppendEntriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tinykv.AppendEntriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 from_id = 1;</code>
   * @return The fromId.
   */
  int getFromId();

  /**
   * <code>int32 to_id = 2;</code>
   * @return The toId.
   */
  int getToId();

  /**
   * <code>int64 term = 3;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <code>bool success = 4;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>int64 match_index = 5;</code>
   * @return The matchIndex.
   */
  long getMatchIndex();
}
