// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Raft.proto

// Protobuf Java Version: 3.25.3
package io.tinykv.proto.raft;

/**
 * Protobuf type {@code tinykv.AppendEntriesRequest}
 */
public final class AppendEntriesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tinykv.AppendEntriesRequest)
    AppendEntriesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppendEntriesRequest.newBuilder() to construct.
  private AppendEntriesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppendEntriesRequest() {
    entries_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AppendEntriesRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_AppendEntriesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_AppendEntriesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.tinykv.proto.raft.AppendEntriesRequest.class, io.tinykv.proto.raft.AppendEntriesRequest.Builder.class);
  }

  public static final int FROM_ID_FIELD_NUMBER = 1;
  private int fromId_ = 0;
  /**
   * <code>int32 from_id = 1;</code>
   * @return The fromId.
   */
  @java.lang.Override
  public int getFromId() {
    return fromId_;
  }

  public static final int TO_ID_FIELD_NUMBER = 2;
  private int toId_ = 0;
  /**
   * <code>int32 to_id = 2;</code>
   * @return The toId.
   */
  @java.lang.Override
  public int getToId() {
    return toId_;
  }

  public static final int TERM_FIELD_NUMBER = 3;
  private long term_ = 0L;
  /**
   * <code>int64 term = 3;</code>
   * @return The term.
   */
  @java.lang.Override
  public long getTerm() {
    return term_;
  }

  public static final int PREV_LOG_INDEX_FIELD_NUMBER = 4;
  private long prevLogIndex_ = 0L;
  /**
   * <code>int64 prev_log_index = 4;</code>
   * @return The prevLogIndex.
   */
  @java.lang.Override
  public long getPrevLogIndex() {
    return prevLogIndex_;
  }

  public static final int PREV_LOG_TERM_FIELD_NUMBER = 5;
  private long prevLogTerm_ = 0L;
  /**
   * <code>int64 prev_log_term = 5;</code>
   * @return The prevLogTerm.
   */
  @java.lang.Override
  public long getPrevLogTerm() {
    return prevLogTerm_;
  }

  public static final int ENTRIES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<io.tinykv.proto.raft.LogEntry> entries_;
  /**
   * <code>repeated .tinykv.LogEntry entries = 6;</code>
   */
  @java.lang.Override
  public java.util.List<io.tinykv.proto.raft.LogEntry> getEntriesList() {
    return entries_;
  }
  /**
   * <code>repeated .tinykv.LogEntry entries = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.tinykv.proto.raft.LogEntryOrBuilder> 
      getEntriesOrBuilderList() {
    return entries_;
  }
  /**
   * <code>repeated .tinykv.LogEntry entries = 6;</code>
   */
  @java.lang.Override
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <code>repeated .tinykv.LogEntry entries = 6;</code>
   */
  @java.lang.Override
  public io.tinykv.proto.raft.LogEntry getEntries(int index) {
    return entries_.get(index);
  }
  /**
   * <code>repeated .tinykv.LogEntry entries = 6;</code>
   */
  @java.lang.Override
  public io.tinykv.proto.raft.LogEntryOrBuilder getEntriesOrBuilder(
      int index) {
    return entries_.get(index);
  }

  public static final int LEADER_COMMIT_FIELD_NUMBER = 7;
  private long leaderCommit_ = 0L;
  /**
   * <code>int64 leader_commit = 7;</code>
   * @return The leaderCommit.
   */
  @java.lang.Override
  public long getLeaderCommit() {
    return leaderCommit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fromId_ != 0) {
      output.writeInt32(1, fromId_);
    }
    if (toId_ != 0) {
      output.writeInt32(2, toId_);
    }
    if (term_ != 0L) {
      output.writeInt64(3, term_);
    }
    if (prevLogIndex_ != 0L) {
      output.writeInt64(4, prevLogIndex_);
    }
    if (prevLogTerm_ != 0L) {
      output.writeInt64(5, prevLogTerm_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      output.writeMessage(6, entries_.get(i));
    }
    if (leaderCommit_ != 0L) {
      output.writeInt64(7, leaderCommit_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fromId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, fromId_);
    }
    if (toId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, toId_);
    }
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, term_);
    }
    if (prevLogIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, prevLogIndex_);
    }
    if (prevLogTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, prevLogTerm_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, entries_.get(i));
    }
    if (leaderCommit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, leaderCommit_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.tinykv.proto.raft.AppendEntriesRequest)) {
      return super.equals(obj);
    }
    io.tinykv.proto.raft.AppendEntriesRequest other = (io.tinykv.proto.raft.AppendEntriesRequest) obj;

    if (getFromId()
        != other.getFromId()) return false;
    if (getToId()
        != other.getToId()) return false;
    if (getTerm()
        != other.getTerm()) return false;
    if (getPrevLogIndex()
        != other.getPrevLogIndex()) return false;
    if (getPrevLogTerm()
        != other.getPrevLogTerm()) return false;
    if (!getEntriesList()
        .equals(other.getEntriesList())) return false;
    if (getLeaderCommit()
        != other.getLeaderCommit()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFromId();
    hash = (37 * hash) + TO_ID_FIELD_NUMBER;
    hash = (53 * hash) + getToId();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    hash = (37 * hash) + PREV_LOG_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrevLogIndex());
    hash = (37 * hash) + PREV_LOG_TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrevLogTerm());
    if (getEntriesCount() > 0) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntriesList().hashCode();
    }
    hash = (37 * hash) + LEADER_COMMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLeaderCommit());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.tinykv.proto.raft.AppendEntriesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.tinykv.proto.raft.AppendEntriesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.tinykv.proto.raft.AppendEntriesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.tinykv.proto.raft.AppendEntriesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.tinykv.proto.raft.AppendEntriesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.tinykv.proto.raft.AppendEntriesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.tinykv.proto.raft.AppendEntriesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.tinykv.proto.raft.AppendEntriesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.tinykv.proto.raft.AppendEntriesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.tinykv.proto.raft.AppendEntriesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.tinykv.proto.raft.AppendEntriesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.tinykv.proto.raft.AppendEntriesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.tinykv.proto.raft.AppendEntriesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tinykv.AppendEntriesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tinykv.AppendEntriesRequest)
      io.tinykv.proto.raft.AppendEntriesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_AppendEntriesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_AppendEntriesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.tinykv.proto.raft.AppendEntriesRequest.class, io.tinykv.proto.raft.AppendEntriesRequest.Builder.class);
    }

    // Construct using io.tinykv.proto.raft.AppendEntriesRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fromId_ = 0;
      toId_ = 0;
      term_ = 0L;
      prevLogIndex_ = 0L;
      prevLogTerm_ = 0L;
      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
      } else {
        entries_ = null;
        entriesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      leaderCommit_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_AppendEntriesRequest_descriptor;
    }

    @java.lang.Override
    public io.tinykv.proto.raft.AppendEntriesRequest getDefaultInstanceForType() {
      return io.tinykv.proto.raft.AppendEntriesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.tinykv.proto.raft.AppendEntriesRequest build() {
      io.tinykv.proto.raft.AppendEntriesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.tinykv.proto.raft.AppendEntriesRequest buildPartial() {
      io.tinykv.proto.raft.AppendEntriesRequest result = new io.tinykv.proto.raft.AppendEntriesRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.tinykv.proto.raft.AppendEntriesRequest result) {
      if (entriesBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.entries_ = entries_;
      } else {
        result.entries_ = entriesBuilder_.build();
      }
    }

    private void buildPartial0(io.tinykv.proto.raft.AppendEntriesRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fromId_ = fromId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.toId_ = toId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.term_ = term_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.prevLogIndex_ = prevLogIndex_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.prevLogTerm_ = prevLogTerm_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.leaderCommit_ = leaderCommit_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.tinykv.proto.raft.AppendEntriesRequest) {
        return mergeFrom((io.tinykv.proto.raft.AppendEntriesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.tinykv.proto.raft.AppendEntriesRequest other) {
      if (other == io.tinykv.proto.raft.AppendEntriesRequest.getDefaultInstance()) return this;
      if (other.getFromId() != 0) {
        setFromId(other.getFromId());
      }
      if (other.getToId() != 0) {
        setToId(other.getToId());
      }
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (other.getPrevLogIndex() != 0L) {
        setPrevLogIndex(other.getPrevLogIndex());
      }
      if (other.getPrevLogTerm() != 0L) {
        setPrevLogTerm(other.getPrevLogTerm());
      }
      if (entriesBuilder_ == null) {
        if (!other.entries_.isEmpty()) {
          if (entries_.isEmpty()) {
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureEntriesIsMutable();
            entries_.addAll(other.entries_);
          }
          onChanged();
        }
      } else {
        if (!other.entries_.isEmpty()) {
          if (entriesBuilder_.isEmpty()) {
            entriesBuilder_.dispose();
            entriesBuilder_ = null;
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000020);
            entriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntriesFieldBuilder() : null;
          } else {
            entriesBuilder_.addAllMessages(other.entries_);
          }
        }
      }
      if (other.getLeaderCommit() != 0L) {
        setLeaderCommit(other.getLeaderCommit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              fromId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              toId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              term_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              prevLogIndex_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              prevLogTerm_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              io.tinykv.proto.raft.LogEntry m =
                  input.readMessage(
                      io.tinykv.proto.raft.LogEntry.parser(),
                      extensionRegistry);
              if (entriesBuilder_ == null) {
                ensureEntriesIsMutable();
                entries_.add(m);
              } else {
                entriesBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 56: {
              leaderCommit_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int fromId_ ;
    /**
     * <code>int32 from_id = 1;</code>
     * @return The fromId.
     */
    @java.lang.Override
    public int getFromId() {
      return fromId_;
    }
    /**
     * <code>int32 from_id = 1;</code>
     * @param value The fromId to set.
     * @return This builder for chaining.
     */
    public Builder setFromId(int value) {

      fromId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 from_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fromId_ = 0;
      onChanged();
      return this;
    }

    private int toId_ ;
    /**
     * <code>int32 to_id = 2;</code>
     * @return The toId.
     */
    @java.lang.Override
    public int getToId() {
      return toId_;
    }
    /**
     * <code>int32 to_id = 2;</code>
     * @param value The toId to set.
     * @return This builder for chaining.
     */
    public Builder setToId(int value) {

      toId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 to_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearToId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      toId_ = 0;
      onChanged();
      return this;
    }

    private long term_ ;
    /**
     * <code>int64 term = 3;</code>
     * @return The term.
     */
    @java.lang.Override
    public long getTerm() {
      return term_;
    }
    /**
     * <code>int64 term = 3;</code>
     * @param value The term to set.
     * @return This builder for chaining.
     */
    public Builder setTerm(long value) {

      term_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 term = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTerm() {
      bitField0_ = (bitField0_ & ~0x00000004);
      term_ = 0L;
      onChanged();
      return this;
    }

    private long prevLogIndex_ ;
    /**
     * <code>int64 prev_log_index = 4;</code>
     * @return The prevLogIndex.
     */
    @java.lang.Override
    public long getPrevLogIndex() {
      return prevLogIndex_;
    }
    /**
     * <code>int64 prev_log_index = 4;</code>
     * @param value The prevLogIndex to set.
     * @return This builder for chaining.
     */
    public Builder setPrevLogIndex(long value) {

      prevLogIndex_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 prev_log_index = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrevLogIndex() {
      bitField0_ = (bitField0_ & ~0x00000008);
      prevLogIndex_ = 0L;
      onChanged();
      return this;
    }

    private long prevLogTerm_ ;
    /**
     * <code>int64 prev_log_term = 5;</code>
     * @return The prevLogTerm.
     */
    @java.lang.Override
    public long getPrevLogTerm() {
      return prevLogTerm_;
    }
    /**
     * <code>int64 prev_log_term = 5;</code>
     * @param value The prevLogTerm to set.
     * @return This builder for chaining.
     */
    public Builder setPrevLogTerm(long value) {

      prevLogTerm_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 prev_log_term = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrevLogTerm() {
      bitField0_ = (bitField0_ & ~0x00000010);
      prevLogTerm_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<io.tinykv.proto.raft.LogEntry> entries_ =
      java.util.Collections.emptyList();
    private void ensureEntriesIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        entries_ = new java.util.ArrayList<io.tinykv.proto.raft.LogEntry>(entries_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.tinykv.proto.raft.LogEntry, io.tinykv.proto.raft.LogEntry.Builder, io.tinykv.proto.raft.LogEntryOrBuilder> entriesBuilder_;

    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public java.util.List<io.tinykv.proto.raft.LogEntry> getEntriesList() {
      if (entriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entries_);
      } else {
        return entriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public int getEntriesCount() {
      if (entriesBuilder_ == null) {
        return entries_.size();
      } else {
        return entriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public io.tinykv.proto.raft.LogEntry getEntries(int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);
      } else {
        return entriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public Builder setEntries(
        int index, io.tinykv.proto.raft.LogEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.set(index, value);
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public Builder setEntries(
        int index, io.tinykv.proto.raft.LogEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.set(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public Builder addEntries(io.tinykv.proto.raft.LogEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public Builder addEntries(
        int index, io.tinykv.proto.raft.LogEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(index, value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public Builder addEntries(
        io.tinykv.proto.raft.LogEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public Builder addEntries(
        int index, io.tinykv.proto.raft.LogEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public Builder addAllEntries(
        java.lang.Iterable<? extends io.tinykv.proto.raft.LogEntry> values) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entries_);
        onChanged();
      } else {
        entriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public Builder clearEntries() {
      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        entriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public Builder removeEntries(int index) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.remove(index);
        onChanged();
      } else {
        entriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public io.tinykv.proto.raft.LogEntry.Builder getEntriesBuilder(
        int index) {
      return getEntriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public io.tinykv.proto.raft.LogEntryOrBuilder getEntriesOrBuilder(
        int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);  } else {
        return entriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public java.util.List<? extends io.tinykv.proto.raft.LogEntryOrBuilder> 
         getEntriesOrBuilderList() {
      if (entriesBuilder_ != null) {
        return entriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entries_);
      }
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public io.tinykv.proto.raft.LogEntry.Builder addEntriesBuilder() {
      return getEntriesFieldBuilder().addBuilder(
          io.tinykv.proto.raft.LogEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public io.tinykv.proto.raft.LogEntry.Builder addEntriesBuilder(
        int index) {
      return getEntriesFieldBuilder().addBuilder(
          index, io.tinykv.proto.raft.LogEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .tinykv.LogEntry entries = 6;</code>
     */
    public java.util.List<io.tinykv.proto.raft.LogEntry.Builder> 
         getEntriesBuilderList() {
      return getEntriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.tinykv.proto.raft.LogEntry, io.tinykv.proto.raft.LogEntry.Builder, io.tinykv.proto.raft.LogEntryOrBuilder> 
        getEntriesFieldBuilder() {
      if (entriesBuilder_ == null) {
        entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.tinykv.proto.raft.LogEntry, io.tinykv.proto.raft.LogEntry.Builder, io.tinykv.proto.raft.LogEntryOrBuilder>(
                entries_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        entries_ = null;
      }
      return entriesBuilder_;
    }

    private long leaderCommit_ ;
    /**
     * <code>int64 leader_commit = 7;</code>
     * @return The leaderCommit.
     */
    @java.lang.Override
    public long getLeaderCommit() {
      return leaderCommit_;
    }
    /**
     * <code>int64 leader_commit = 7;</code>
     * @param value The leaderCommit to set.
     * @return This builder for chaining.
     */
    public Builder setLeaderCommit(long value) {

      leaderCommit_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 leader_commit = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeaderCommit() {
      bitField0_ = (bitField0_ & ~0x00000040);
      leaderCommit_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tinykv.AppendEntriesRequest)
  }

  // @@protoc_insertion_point(class_scope:tinykv.AppendEntriesRequest)
  private static final io.tinykv.proto.raft.AppendEntriesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.tinykv.proto.raft.AppendEntriesRequest();
  }

  public static io.tinykv.proto.raft.AppendEntriesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppendEntriesRequest>
      PARSER = new com.google.protobuf.AbstractParser<AppendEntriesRequest>() {
    @java.lang.Override
    public AppendEntriesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AppendEntriesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppendEntriesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.tinykv.proto.raft.AppendEntriesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

