// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Raft.proto

// Protobuf Java Version: 3.25.3
package io.tinykv.proto.raft;

/**
 * Protobuf type {@code tinykv.RaftMessage}
 */
public final class RaftMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tinykv.RaftMessage)
    RaftMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RaftMessage.newBuilder() to construct.
  private RaftMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RaftMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RaftMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_RaftMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_RaftMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.tinykv.proto.raft.RaftMessage.class, io.tinykv.proto.raft.RaftMessage.Builder.class);
  }

  private int msgCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    REQUEST_VOTE(1),
    REQUEST_VOTE_RESPONSE(2),
    APPEND_ENTRIES(3),
    APPEND_ENTRIES_RESPONSE(4),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 1: return REQUEST_VOTE;
        case 2: return REQUEST_VOTE_RESPONSE;
        case 3: return APPEND_ENTRIES;
        case 4: return APPEND_ENTRIES_RESPONSE;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int REQUEST_VOTE_FIELD_NUMBER = 1;
  /**
   * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
   * @return Whether the requestVote field is set.
   */
  @java.lang.Override
  public boolean hasRequestVote() {
    return msgCase_ == 1;
  }
  /**
   * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
   * @return The requestVote.
   */
  @java.lang.Override
  public io.tinykv.proto.raft.RequestVoteRequest getRequestVote() {
    if (msgCase_ == 1) {
       return (io.tinykv.proto.raft.RequestVoteRequest) msg_;
    }
    return io.tinykv.proto.raft.RequestVoteRequest.getDefaultInstance();
  }
  /**
   * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
   */
  @java.lang.Override
  public io.tinykv.proto.raft.RequestVoteRequestOrBuilder getRequestVoteOrBuilder() {
    if (msgCase_ == 1) {
       return (io.tinykv.proto.raft.RequestVoteRequest) msg_;
    }
    return io.tinykv.proto.raft.RequestVoteRequest.getDefaultInstance();
  }

  public static final int REQUEST_VOTE_RESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
   * @return Whether the requestVoteResponse field is set.
   */
  @java.lang.Override
  public boolean hasRequestVoteResponse() {
    return msgCase_ == 2;
  }
  /**
   * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
   * @return The requestVoteResponse.
   */
  @java.lang.Override
  public io.tinykv.proto.raft.RequestVoteResponse getRequestVoteResponse() {
    if (msgCase_ == 2) {
       return (io.tinykv.proto.raft.RequestVoteResponse) msg_;
    }
    return io.tinykv.proto.raft.RequestVoteResponse.getDefaultInstance();
  }
  /**
   * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
   */
  @java.lang.Override
  public io.tinykv.proto.raft.RequestVoteResponseOrBuilder getRequestVoteResponseOrBuilder() {
    if (msgCase_ == 2) {
       return (io.tinykv.proto.raft.RequestVoteResponse) msg_;
    }
    return io.tinykv.proto.raft.RequestVoteResponse.getDefaultInstance();
  }

  public static final int APPEND_ENTRIES_FIELD_NUMBER = 3;
  /**
   * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
   * @return Whether the appendEntries field is set.
   */
  @java.lang.Override
  public boolean hasAppendEntries() {
    return msgCase_ == 3;
  }
  /**
   * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
   * @return The appendEntries.
   */
  @java.lang.Override
  public io.tinykv.proto.raft.AppendEntriesRequest getAppendEntries() {
    if (msgCase_ == 3) {
       return (io.tinykv.proto.raft.AppendEntriesRequest) msg_;
    }
    return io.tinykv.proto.raft.AppendEntriesRequest.getDefaultInstance();
  }
  /**
   * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
   */
  @java.lang.Override
  public io.tinykv.proto.raft.AppendEntriesRequestOrBuilder getAppendEntriesOrBuilder() {
    if (msgCase_ == 3) {
       return (io.tinykv.proto.raft.AppendEntriesRequest) msg_;
    }
    return io.tinykv.proto.raft.AppendEntriesRequest.getDefaultInstance();
  }

  public static final int APPEND_ENTRIES_RESPONSE_FIELD_NUMBER = 4;
  /**
   * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
   * @return Whether the appendEntriesResponse field is set.
   */
  @java.lang.Override
  public boolean hasAppendEntriesResponse() {
    return msgCase_ == 4;
  }
  /**
   * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
   * @return The appendEntriesResponse.
   */
  @java.lang.Override
  public io.tinykv.proto.raft.AppendEntriesResponse getAppendEntriesResponse() {
    if (msgCase_ == 4) {
       return (io.tinykv.proto.raft.AppendEntriesResponse) msg_;
    }
    return io.tinykv.proto.raft.AppendEntriesResponse.getDefaultInstance();
  }
  /**
   * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
   */
  @java.lang.Override
  public io.tinykv.proto.raft.AppendEntriesResponseOrBuilder getAppendEntriesResponseOrBuilder() {
    if (msgCase_ == 4) {
       return (io.tinykv.proto.raft.AppendEntriesResponse) msg_;
    }
    return io.tinykv.proto.raft.AppendEntriesResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgCase_ == 1) {
      output.writeMessage(1, (io.tinykv.proto.raft.RequestVoteRequest) msg_);
    }
    if (msgCase_ == 2) {
      output.writeMessage(2, (io.tinykv.proto.raft.RequestVoteResponse) msg_);
    }
    if (msgCase_ == 3) {
      output.writeMessage(3, (io.tinykv.proto.raft.AppendEntriesRequest) msg_);
    }
    if (msgCase_ == 4) {
      output.writeMessage(4, (io.tinykv.proto.raft.AppendEntriesResponse) msg_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (io.tinykv.proto.raft.RequestVoteRequest) msg_);
    }
    if (msgCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.tinykv.proto.raft.RequestVoteResponse) msg_);
    }
    if (msgCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (io.tinykv.proto.raft.AppendEntriesRequest) msg_);
    }
    if (msgCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (io.tinykv.proto.raft.AppendEntriesResponse) msg_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.tinykv.proto.raft.RaftMessage)) {
      return super.equals(obj);
    }
    io.tinykv.proto.raft.RaftMessage other = (io.tinykv.proto.raft.RaftMessage) obj;

    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 1:
        if (!getRequestVote()
            .equals(other.getRequestVote())) return false;
        break;
      case 2:
        if (!getRequestVoteResponse()
            .equals(other.getRequestVoteResponse())) return false;
        break;
      case 3:
        if (!getAppendEntries()
            .equals(other.getAppendEntries())) return false;
        break;
      case 4:
        if (!getAppendEntriesResponse()
            .equals(other.getAppendEntriesResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (msgCase_) {
      case 1:
        hash = (37 * hash) + REQUEST_VOTE_FIELD_NUMBER;
        hash = (53 * hash) + getRequestVote().hashCode();
        break;
      case 2:
        hash = (37 * hash) + REQUEST_VOTE_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getRequestVoteResponse().hashCode();
        break;
      case 3:
        hash = (37 * hash) + APPEND_ENTRIES_FIELD_NUMBER;
        hash = (53 * hash) + getAppendEntries().hashCode();
        break;
      case 4:
        hash = (37 * hash) + APPEND_ENTRIES_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getAppendEntriesResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.tinykv.proto.raft.RaftMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.tinykv.proto.raft.RaftMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.tinykv.proto.raft.RaftMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.tinykv.proto.raft.RaftMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.tinykv.proto.raft.RaftMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.tinykv.proto.raft.RaftMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.tinykv.proto.raft.RaftMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.tinykv.proto.raft.RaftMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.tinykv.proto.raft.RaftMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.tinykv.proto.raft.RaftMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.tinykv.proto.raft.RaftMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.tinykv.proto.raft.RaftMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.tinykv.proto.raft.RaftMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tinykv.RaftMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tinykv.RaftMessage)
      io.tinykv.proto.raft.RaftMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_RaftMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_RaftMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.tinykv.proto.raft.RaftMessage.class, io.tinykv.proto.raft.RaftMessage.Builder.class);
    }

    // Construct using io.tinykv.proto.raft.RaftMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (requestVoteBuilder_ != null) {
        requestVoteBuilder_.clear();
      }
      if (requestVoteResponseBuilder_ != null) {
        requestVoteResponseBuilder_.clear();
      }
      if (appendEntriesBuilder_ != null) {
        appendEntriesBuilder_.clear();
      }
      if (appendEntriesResponseBuilder_ != null) {
        appendEntriesResponseBuilder_.clear();
      }
      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_RaftMessage_descriptor;
    }

    @java.lang.Override
    public io.tinykv.proto.raft.RaftMessage getDefaultInstanceForType() {
      return io.tinykv.proto.raft.RaftMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.tinykv.proto.raft.RaftMessage build() {
      io.tinykv.proto.raft.RaftMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.tinykv.proto.raft.RaftMessage buildPartial() {
      io.tinykv.proto.raft.RaftMessage result = new io.tinykv.proto.raft.RaftMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(io.tinykv.proto.raft.RaftMessage result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(io.tinykv.proto.raft.RaftMessage result) {
      result.msgCase_ = msgCase_;
      result.msg_ = this.msg_;
      if (msgCase_ == 1 &&
          requestVoteBuilder_ != null) {
        result.msg_ = requestVoteBuilder_.build();
      }
      if (msgCase_ == 2 &&
          requestVoteResponseBuilder_ != null) {
        result.msg_ = requestVoteResponseBuilder_.build();
      }
      if (msgCase_ == 3 &&
          appendEntriesBuilder_ != null) {
        result.msg_ = appendEntriesBuilder_.build();
      }
      if (msgCase_ == 4 &&
          appendEntriesResponseBuilder_ != null) {
        result.msg_ = appendEntriesResponseBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.tinykv.proto.raft.RaftMessage) {
        return mergeFrom((io.tinykv.proto.raft.RaftMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.tinykv.proto.raft.RaftMessage other) {
      if (other == io.tinykv.proto.raft.RaftMessage.getDefaultInstance()) return this;
      switch (other.getMsgCase()) {
        case REQUEST_VOTE: {
          mergeRequestVote(other.getRequestVote());
          break;
        }
        case REQUEST_VOTE_RESPONSE: {
          mergeRequestVoteResponse(other.getRequestVoteResponse());
          break;
        }
        case APPEND_ENTRIES: {
          mergeAppendEntries(other.getAppendEntries());
          break;
        }
        case APPEND_ENTRIES_RESPONSE: {
          mergeAppendEntriesResponse(other.getAppendEntriesResponse());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getRequestVoteFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getRequestVoteResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getAppendEntriesFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getAppendEntriesResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        io.tinykv.proto.raft.RequestVoteRequest, io.tinykv.proto.raft.RequestVoteRequest.Builder, io.tinykv.proto.raft.RequestVoteRequestOrBuilder> requestVoteBuilder_;
    /**
     * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
     * @return Whether the requestVote field is set.
     */
    @java.lang.Override
    public boolean hasRequestVote() {
      return msgCase_ == 1;
    }
    /**
     * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
     * @return The requestVote.
     */
    @java.lang.Override
    public io.tinykv.proto.raft.RequestVoteRequest getRequestVote() {
      if (requestVoteBuilder_ == null) {
        if (msgCase_ == 1) {
          return (io.tinykv.proto.raft.RequestVoteRequest) msg_;
        }
        return io.tinykv.proto.raft.RequestVoteRequest.getDefaultInstance();
      } else {
        if (msgCase_ == 1) {
          return requestVoteBuilder_.getMessage();
        }
        return io.tinykv.proto.raft.RequestVoteRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
     */
    public Builder setRequestVote(io.tinykv.proto.raft.RequestVoteRequest value) {
      if (requestVoteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        requestVoteBuilder_.setMessage(value);
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
     */
    public Builder setRequestVote(
        io.tinykv.proto.raft.RequestVoteRequest.Builder builderForValue) {
      if (requestVoteBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        requestVoteBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
     */
    public Builder mergeRequestVote(io.tinykv.proto.raft.RequestVoteRequest value) {
      if (requestVoteBuilder_ == null) {
        if (msgCase_ == 1 &&
            msg_ != io.tinykv.proto.raft.RequestVoteRequest.getDefaultInstance()) {
          msg_ = io.tinykv.proto.raft.RequestVoteRequest.newBuilder((io.tinykv.proto.raft.RequestVoteRequest) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 1) {
          requestVoteBuilder_.mergeFrom(value);
        } else {
          requestVoteBuilder_.setMessage(value);
        }
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
     */
    public Builder clearRequestVote() {
      if (requestVoteBuilder_ == null) {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
        }
        requestVoteBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
     */
    public io.tinykv.proto.raft.RequestVoteRequest.Builder getRequestVoteBuilder() {
      return getRequestVoteFieldBuilder().getBuilder();
    }
    /**
     * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
     */
    @java.lang.Override
    public io.tinykv.proto.raft.RequestVoteRequestOrBuilder getRequestVoteOrBuilder() {
      if ((msgCase_ == 1) && (requestVoteBuilder_ != null)) {
        return requestVoteBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 1) {
          return (io.tinykv.proto.raft.RequestVoteRequest) msg_;
        }
        return io.tinykv.proto.raft.RequestVoteRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.tinykv.proto.raft.RequestVoteRequest, io.tinykv.proto.raft.RequestVoteRequest.Builder, io.tinykv.proto.raft.RequestVoteRequestOrBuilder> 
        getRequestVoteFieldBuilder() {
      if (requestVoteBuilder_ == null) {
        if (!(msgCase_ == 1)) {
          msg_ = io.tinykv.proto.raft.RequestVoteRequest.getDefaultInstance();
        }
        requestVoteBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.tinykv.proto.raft.RequestVoteRequest, io.tinykv.proto.raft.RequestVoteRequest.Builder, io.tinykv.proto.raft.RequestVoteRequestOrBuilder>(
                (io.tinykv.proto.raft.RequestVoteRequest) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 1;
      onChanged();
      return requestVoteBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.tinykv.proto.raft.RequestVoteResponse, io.tinykv.proto.raft.RequestVoteResponse.Builder, io.tinykv.proto.raft.RequestVoteResponseOrBuilder> requestVoteResponseBuilder_;
    /**
     * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
     * @return Whether the requestVoteResponse field is set.
     */
    @java.lang.Override
    public boolean hasRequestVoteResponse() {
      return msgCase_ == 2;
    }
    /**
     * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
     * @return The requestVoteResponse.
     */
    @java.lang.Override
    public io.tinykv.proto.raft.RequestVoteResponse getRequestVoteResponse() {
      if (requestVoteResponseBuilder_ == null) {
        if (msgCase_ == 2) {
          return (io.tinykv.proto.raft.RequestVoteResponse) msg_;
        }
        return io.tinykv.proto.raft.RequestVoteResponse.getDefaultInstance();
      } else {
        if (msgCase_ == 2) {
          return requestVoteResponseBuilder_.getMessage();
        }
        return io.tinykv.proto.raft.RequestVoteResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
     */
    public Builder setRequestVoteResponse(io.tinykv.proto.raft.RequestVoteResponse value) {
      if (requestVoteResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        requestVoteResponseBuilder_.setMessage(value);
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
     */
    public Builder setRequestVoteResponse(
        io.tinykv.proto.raft.RequestVoteResponse.Builder builderForValue) {
      if (requestVoteResponseBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        requestVoteResponseBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
     */
    public Builder mergeRequestVoteResponse(io.tinykv.proto.raft.RequestVoteResponse value) {
      if (requestVoteResponseBuilder_ == null) {
        if (msgCase_ == 2 &&
            msg_ != io.tinykv.proto.raft.RequestVoteResponse.getDefaultInstance()) {
          msg_ = io.tinykv.proto.raft.RequestVoteResponse.newBuilder((io.tinykv.proto.raft.RequestVoteResponse) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 2) {
          requestVoteResponseBuilder_.mergeFrom(value);
        } else {
          requestVoteResponseBuilder_.setMessage(value);
        }
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
     */
    public Builder clearRequestVoteResponse() {
      if (requestVoteResponseBuilder_ == null) {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
        }
        requestVoteResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
     */
    public io.tinykv.proto.raft.RequestVoteResponse.Builder getRequestVoteResponseBuilder() {
      return getRequestVoteResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
     */
    @java.lang.Override
    public io.tinykv.proto.raft.RequestVoteResponseOrBuilder getRequestVoteResponseOrBuilder() {
      if ((msgCase_ == 2) && (requestVoteResponseBuilder_ != null)) {
        return requestVoteResponseBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 2) {
          return (io.tinykv.proto.raft.RequestVoteResponse) msg_;
        }
        return io.tinykv.proto.raft.RequestVoteResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.tinykv.proto.raft.RequestVoteResponse, io.tinykv.proto.raft.RequestVoteResponse.Builder, io.tinykv.proto.raft.RequestVoteResponseOrBuilder> 
        getRequestVoteResponseFieldBuilder() {
      if (requestVoteResponseBuilder_ == null) {
        if (!(msgCase_ == 2)) {
          msg_ = io.tinykv.proto.raft.RequestVoteResponse.getDefaultInstance();
        }
        requestVoteResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.tinykv.proto.raft.RequestVoteResponse, io.tinykv.proto.raft.RequestVoteResponse.Builder, io.tinykv.proto.raft.RequestVoteResponseOrBuilder>(
                (io.tinykv.proto.raft.RequestVoteResponse) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 2;
      onChanged();
      return requestVoteResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.tinykv.proto.raft.AppendEntriesRequest, io.tinykv.proto.raft.AppendEntriesRequest.Builder, io.tinykv.proto.raft.AppendEntriesRequestOrBuilder> appendEntriesBuilder_;
    /**
     * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
     * @return Whether the appendEntries field is set.
     */
    @java.lang.Override
    public boolean hasAppendEntries() {
      return msgCase_ == 3;
    }
    /**
     * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
     * @return The appendEntries.
     */
    @java.lang.Override
    public io.tinykv.proto.raft.AppendEntriesRequest getAppendEntries() {
      if (appendEntriesBuilder_ == null) {
        if (msgCase_ == 3) {
          return (io.tinykv.proto.raft.AppendEntriesRequest) msg_;
        }
        return io.tinykv.proto.raft.AppendEntriesRequest.getDefaultInstance();
      } else {
        if (msgCase_ == 3) {
          return appendEntriesBuilder_.getMessage();
        }
        return io.tinykv.proto.raft.AppendEntriesRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
     */
    public Builder setAppendEntries(io.tinykv.proto.raft.AppendEntriesRequest value) {
      if (appendEntriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        appendEntriesBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
     */
    public Builder setAppendEntries(
        io.tinykv.proto.raft.AppendEntriesRequest.Builder builderForValue) {
      if (appendEntriesBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        appendEntriesBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
     */
    public Builder mergeAppendEntries(io.tinykv.proto.raft.AppendEntriesRequest value) {
      if (appendEntriesBuilder_ == null) {
        if (msgCase_ == 3 &&
            msg_ != io.tinykv.proto.raft.AppendEntriesRequest.getDefaultInstance()) {
          msg_ = io.tinykv.proto.raft.AppendEntriesRequest.newBuilder((io.tinykv.proto.raft.AppendEntriesRequest) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 3) {
          appendEntriesBuilder_.mergeFrom(value);
        } else {
          appendEntriesBuilder_.setMessage(value);
        }
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
     */
    public Builder clearAppendEntries() {
      if (appendEntriesBuilder_ == null) {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
        }
        appendEntriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
     */
    public io.tinykv.proto.raft.AppendEntriesRequest.Builder getAppendEntriesBuilder() {
      return getAppendEntriesFieldBuilder().getBuilder();
    }
    /**
     * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
     */
    @java.lang.Override
    public io.tinykv.proto.raft.AppendEntriesRequestOrBuilder getAppendEntriesOrBuilder() {
      if ((msgCase_ == 3) && (appendEntriesBuilder_ != null)) {
        return appendEntriesBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 3) {
          return (io.tinykv.proto.raft.AppendEntriesRequest) msg_;
        }
        return io.tinykv.proto.raft.AppendEntriesRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.tinykv.proto.raft.AppendEntriesRequest, io.tinykv.proto.raft.AppendEntriesRequest.Builder, io.tinykv.proto.raft.AppendEntriesRequestOrBuilder> 
        getAppendEntriesFieldBuilder() {
      if (appendEntriesBuilder_ == null) {
        if (!(msgCase_ == 3)) {
          msg_ = io.tinykv.proto.raft.AppendEntriesRequest.getDefaultInstance();
        }
        appendEntriesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.tinykv.proto.raft.AppendEntriesRequest, io.tinykv.proto.raft.AppendEntriesRequest.Builder, io.tinykv.proto.raft.AppendEntriesRequestOrBuilder>(
                (io.tinykv.proto.raft.AppendEntriesRequest) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 3;
      onChanged();
      return appendEntriesBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.tinykv.proto.raft.AppendEntriesResponse, io.tinykv.proto.raft.AppendEntriesResponse.Builder, io.tinykv.proto.raft.AppendEntriesResponseOrBuilder> appendEntriesResponseBuilder_;
    /**
     * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
     * @return Whether the appendEntriesResponse field is set.
     */
    @java.lang.Override
    public boolean hasAppendEntriesResponse() {
      return msgCase_ == 4;
    }
    /**
     * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
     * @return The appendEntriesResponse.
     */
    @java.lang.Override
    public io.tinykv.proto.raft.AppendEntriesResponse getAppendEntriesResponse() {
      if (appendEntriesResponseBuilder_ == null) {
        if (msgCase_ == 4) {
          return (io.tinykv.proto.raft.AppendEntriesResponse) msg_;
        }
        return io.tinykv.proto.raft.AppendEntriesResponse.getDefaultInstance();
      } else {
        if (msgCase_ == 4) {
          return appendEntriesResponseBuilder_.getMessage();
        }
        return io.tinykv.proto.raft.AppendEntriesResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
     */
    public Builder setAppendEntriesResponse(io.tinykv.proto.raft.AppendEntriesResponse value) {
      if (appendEntriesResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        appendEntriesResponseBuilder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
     */
    public Builder setAppendEntriesResponse(
        io.tinykv.proto.raft.AppendEntriesResponse.Builder builderForValue) {
      if (appendEntriesResponseBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        appendEntriesResponseBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
     */
    public Builder mergeAppendEntriesResponse(io.tinykv.proto.raft.AppendEntriesResponse value) {
      if (appendEntriesResponseBuilder_ == null) {
        if (msgCase_ == 4 &&
            msg_ != io.tinykv.proto.raft.AppendEntriesResponse.getDefaultInstance()) {
          msg_ = io.tinykv.proto.raft.AppendEntriesResponse.newBuilder((io.tinykv.proto.raft.AppendEntriesResponse) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 4) {
          appendEntriesResponseBuilder_.mergeFrom(value);
        } else {
          appendEntriesResponseBuilder_.setMessage(value);
        }
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
     */
    public Builder clearAppendEntriesResponse() {
      if (appendEntriesResponseBuilder_ == null) {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
        }
        appendEntriesResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
     */
    public io.tinykv.proto.raft.AppendEntriesResponse.Builder getAppendEntriesResponseBuilder() {
      return getAppendEntriesResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
     */
    @java.lang.Override
    public io.tinykv.proto.raft.AppendEntriesResponseOrBuilder getAppendEntriesResponseOrBuilder() {
      if ((msgCase_ == 4) && (appendEntriesResponseBuilder_ != null)) {
        return appendEntriesResponseBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 4) {
          return (io.tinykv.proto.raft.AppendEntriesResponse) msg_;
        }
        return io.tinykv.proto.raft.AppendEntriesResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.tinykv.proto.raft.AppendEntriesResponse, io.tinykv.proto.raft.AppendEntriesResponse.Builder, io.tinykv.proto.raft.AppendEntriesResponseOrBuilder> 
        getAppendEntriesResponseFieldBuilder() {
      if (appendEntriesResponseBuilder_ == null) {
        if (!(msgCase_ == 4)) {
          msg_ = io.tinykv.proto.raft.AppendEntriesResponse.getDefaultInstance();
        }
        appendEntriesResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.tinykv.proto.raft.AppendEntriesResponse, io.tinykv.proto.raft.AppendEntriesResponse.Builder, io.tinykv.proto.raft.AppendEntriesResponseOrBuilder>(
                (io.tinykv.proto.raft.AppendEntriesResponse) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 4;
      onChanged();
      return appendEntriesResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tinykv.RaftMessage)
  }

  // @@protoc_insertion_point(class_scope:tinykv.RaftMessage)
  private static final io.tinykv.proto.raft.RaftMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.tinykv.proto.raft.RaftMessage();
  }

  public static io.tinykv.proto.raft.RaftMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RaftMessage>
      PARSER = new com.google.protobuf.AbstractParser<RaftMessage>() {
    @java.lang.Override
    public RaftMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RaftMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RaftMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.tinykv.proto.raft.RaftMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

