// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Raft.proto

// Protobuf Java Version: 3.25.3
package io.tinykv.proto.raft;

public interface RaftMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tinykv.RaftMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
   * @return Whether the requestVote field is set.
   */
  boolean hasRequestVote();
  /**
   * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
   * @return The requestVote.
   */
  io.tinykv.proto.raft.RequestVoteRequest getRequestVote();
  /**
   * <code>.tinykv.RequestVoteRequest request_vote = 1;</code>
   */
  io.tinykv.proto.raft.RequestVoteRequestOrBuilder getRequestVoteOrBuilder();

  /**
   * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
   * @return Whether the requestVoteResponse field is set.
   */
  boolean hasRequestVoteResponse();
  /**
   * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
   * @return The requestVoteResponse.
   */
  io.tinykv.proto.raft.RequestVoteResponse getRequestVoteResponse();
  /**
   * <code>.tinykv.RequestVoteResponse request_vote_response = 2;</code>
   */
  io.tinykv.proto.raft.RequestVoteResponseOrBuilder getRequestVoteResponseOrBuilder();

  /**
   * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
   * @return Whether the appendEntries field is set.
   */
  boolean hasAppendEntries();
  /**
   * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
   * @return The appendEntries.
   */
  io.tinykv.proto.raft.AppendEntriesRequest getAppendEntries();
  /**
   * <code>.tinykv.AppendEntriesRequest append_entries = 3;</code>
   */
  io.tinykv.proto.raft.AppendEntriesRequestOrBuilder getAppendEntriesOrBuilder();

  /**
   * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
   * @return Whether the appendEntriesResponse field is set.
   */
  boolean hasAppendEntriesResponse();
  /**
   * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
   * @return The appendEntriesResponse.
   */
  io.tinykv.proto.raft.AppendEntriesResponse getAppendEntriesResponse();
  /**
   * <code>.tinykv.AppendEntriesResponse append_entries_response = 4;</code>
   */
  io.tinykv.proto.raft.AppendEntriesResponseOrBuilder getAppendEntriesResponseOrBuilder();

  io.tinykv.proto.raft.RaftMessage.MsgCase getMsgCase();
}
