// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Raft.proto

// Protobuf Java Version: 3.25.3
package io.tinykv.proto.raft;

public final class RaftProto {
  private RaftProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinykv_RequestVoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinykv_RequestVoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinykv_RequestVoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinykv_RequestVoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinykv_AppendEntriesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinykv_AppendEntriesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinykv_AppendEntriesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinykv_AppendEntriesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinykv_LogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinykv_LogEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinykv_RaftMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinykv_RaftMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRaft.proto\022\006tinykv\"q\n\022RequestVoteReque" +
      "st\022\017\n\007from_id\030\001 \001(\005\022\r\n\005to_id\030\002 \001(\005\022\014\n\004te" +
      "rm\030\003 \001(\003\022\026\n\016last_log_index\030\004 \001(\003\022\025\n\rlast" +
      "_log_term\030\005 \001(\003\"Y\n\023RequestVoteResponse\022\017" +
      "\n\007from_id\030\001 \001(\005\022\r\n\005to_id\030\002 \001(\005\022\014\n\004term\030\003" +
      " \001(\003\022\024\n\014vote_granted\030\004 \001(\010\"\255\001\n\024AppendEnt" +
      "riesRequest\022\017\n\007from_id\030\001 \001(\005\022\r\n\005to_id\030\002 " +
      "\001(\005\022\014\n\004term\030\003 \001(\003\022\026\n\016prev_log_index\030\004 \001(" +
      "\003\022\025\n\rprev_log_term\030\005 \001(\003\022!\n\007entries\030\006 \003(" +
      "\0132\020.tinykv.LogEntry\022\025\n\rleader_commit\030\007 \001" +
      "(\003\"k\n\025AppendEntriesResponse\022\017\n\007from_id\030\001" +
      " \001(\005\022\r\n\005to_id\030\002 \001(\005\022\014\n\004term\030\003 \001(\003\022\017\n\007suc" +
      "cess\030\004 \001(\010\022\023\n\013match_index\030\005 \001(\003\"5\n\010LogEn" +
      "try\022\014\n\004term\030\001 \001(\003\022\r\n\005index\030\002 \001(\003\022\014\n\004data" +
      "\030\003 \001(\014\"\200\002\n\013RaftMessage\0222\n\014request_vote\030\001" +
      " \001(\0132\032.tinykv.RequestVoteRequestH\000\022<\n\025re" +
      "quest_vote_response\030\002 \001(\0132\033.tinykv.Reque" +
      "stVoteResponseH\000\0226\n\016append_entries\030\003 \001(\013" +
      "2\034.tinykv.AppendEntriesRequestH\000\022@\n\027appe" +
      "nd_entries_response\030\004 \001(\0132\035.tinykv.Appen" +
      "dEntriesResponseH\000B\005\n\003msg2\262\001\n\016RaftRpcSer" +
      "vice\022L\n\021HandleRequestVote\022\032.tinykv.Reque" +
      "stVoteRequest\032\033.tinykv.RequestVoteRespon" +
      "se\022R\n\023HandleAppendEntries\022\034.tinykv.Appen" +
      "dEntriesRequest\032\035.tinykv.AppendEntriesRe" +
      "sponseB#\n\024io.tinykv.proto.raftB\tRaftProt" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tinykv_RequestVoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tinykv_RequestVoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinykv_RequestVoteRequest_descriptor,
        new java.lang.String[] { "FromId", "ToId", "Term", "LastLogIndex", "LastLogTerm", });
    internal_static_tinykv_RequestVoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tinykv_RequestVoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinykv_RequestVoteResponse_descriptor,
        new java.lang.String[] { "FromId", "ToId", "Term", "VoteGranted", });
    internal_static_tinykv_AppendEntriesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tinykv_AppendEntriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinykv_AppendEntriesRequest_descriptor,
        new java.lang.String[] { "FromId", "ToId", "Term", "PrevLogIndex", "PrevLogTerm", "Entries", "LeaderCommit", });
    internal_static_tinykv_AppendEntriesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tinykv_AppendEntriesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinykv_AppendEntriesResponse_descriptor,
        new java.lang.String[] { "FromId", "ToId", "Term", "Success", "MatchIndex", });
    internal_static_tinykv_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tinykv_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinykv_LogEntry_descriptor,
        new java.lang.String[] { "Term", "Index", "Data", });
    internal_static_tinykv_RaftMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tinykv_RaftMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinykv_RaftMessage_descriptor,
        new java.lang.String[] { "RequestVote", "RequestVoteResponse", "AppendEntries", "AppendEntriesResponse", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
