// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Raft.proto

// Protobuf Java Version: 3.25.3
package io.tinykv.proto.raft;

/**
 * <pre>
 * Raft message types
 * </pre>
 *
 * Protobuf type {@code tinykv.RequestVoteRequest}
 */
public final class RequestVoteRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tinykv.RequestVoteRequest)
    RequestVoteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestVoteRequest.newBuilder() to construct.
  private RequestVoteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestVoteRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestVoteRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_RequestVoteRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_RequestVoteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.tinykv.proto.raft.RequestVoteRequest.class, io.tinykv.proto.raft.RequestVoteRequest.Builder.class);
  }

  public static final int FROM_ID_FIELD_NUMBER = 1;
  private int fromId_ = 0;
  /**
   * <code>int32 from_id = 1;</code>
   * @return The fromId.
   */
  @java.lang.Override
  public int getFromId() {
    return fromId_;
  }

  public static final int TO_ID_FIELD_NUMBER = 2;
  private int toId_ = 0;
  /**
   * <code>int32 to_id = 2;</code>
   * @return The toId.
   */
  @java.lang.Override
  public int getToId() {
    return toId_;
  }

  public static final int TERM_FIELD_NUMBER = 3;
  private long term_ = 0L;
  /**
   * <code>int64 term = 3;</code>
   * @return The term.
   */
  @java.lang.Override
  public long getTerm() {
    return term_;
  }

  public static final int LAST_LOG_INDEX_FIELD_NUMBER = 4;
  private long lastLogIndex_ = 0L;
  /**
   * <code>int64 last_log_index = 4;</code>
   * @return The lastLogIndex.
   */
  @java.lang.Override
  public long getLastLogIndex() {
    return lastLogIndex_;
  }

  public static final int LAST_LOG_TERM_FIELD_NUMBER = 5;
  private long lastLogTerm_ = 0L;
  /**
   * <code>int64 last_log_term = 5;</code>
   * @return The lastLogTerm.
   */
  @java.lang.Override
  public long getLastLogTerm() {
    return lastLogTerm_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fromId_ != 0) {
      output.writeInt32(1, fromId_);
    }
    if (toId_ != 0) {
      output.writeInt32(2, toId_);
    }
    if (term_ != 0L) {
      output.writeInt64(3, term_);
    }
    if (lastLogIndex_ != 0L) {
      output.writeInt64(4, lastLogIndex_);
    }
    if (lastLogTerm_ != 0L) {
      output.writeInt64(5, lastLogTerm_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fromId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, fromId_);
    }
    if (toId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, toId_);
    }
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, term_);
    }
    if (lastLogIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, lastLogIndex_);
    }
    if (lastLogTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, lastLogTerm_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.tinykv.proto.raft.RequestVoteRequest)) {
      return super.equals(obj);
    }
    io.tinykv.proto.raft.RequestVoteRequest other = (io.tinykv.proto.raft.RequestVoteRequest) obj;

    if (getFromId()
        != other.getFromId()) return false;
    if (getToId()
        != other.getToId()) return false;
    if (getTerm()
        != other.getTerm()) return false;
    if (getLastLogIndex()
        != other.getLastLogIndex()) return false;
    if (getLastLogTerm()
        != other.getLastLogTerm()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFromId();
    hash = (37 * hash) + TO_ID_FIELD_NUMBER;
    hash = (53 * hash) + getToId();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    hash = (37 * hash) + LAST_LOG_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLogIndex());
    hash = (37 * hash) + LAST_LOG_TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLogTerm());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.tinykv.proto.raft.RequestVoteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.tinykv.proto.raft.RequestVoteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.tinykv.proto.raft.RequestVoteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.tinykv.proto.raft.RequestVoteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.tinykv.proto.raft.RequestVoteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.tinykv.proto.raft.RequestVoteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.tinykv.proto.raft.RequestVoteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.tinykv.proto.raft.RequestVoteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.tinykv.proto.raft.RequestVoteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.tinykv.proto.raft.RequestVoteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.tinykv.proto.raft.RequestVoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.tinykv.proto.raft.RequestVoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.tinykv.proto.raft.RequestVoteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Raft message types
   * </pre>
   *
   * Protobuf type {@code tinykv.RequestVoteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tinykv.RequestVoteRequest)
      io.tinykv.proto.raft.RequestVoteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_RequestVoteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_RequestVoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.tinykv.proto.raft.RequestVoteRequest.class, io.tinykv.proto.raft.RequestVoteRequest.Builder.class);
    }

    // Construct using io.tinykv.proto.raft.RequestVoteRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fromId_ = 0;
      toId_ = 0;
      term_ = 0L;
      lastLogIndex_ = 0L;
      lastLogTerm_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.tinykv.proto.raft.RaftProto.internal_static_tinykv_RequestVoteRequest_descriptor;
    }

    @java.lang.Override
    public io.tinykv.proto.raft.RequestVoteRequest getDefaultInstanceForType() {
      return io.tinykv.proto.raft.RequestVoteRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.tinykv.proto.raft.RequestVoteRequest build() {
      io.tinykv.proto.raft.RequestVoteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.tinykv.proto.raft.RequestVoteRequest buildPartial() {
      io.tinykv.proto.raft.RequestVoteRequest result = new io.tinykv.proto.raft.RequestVoteRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.tinykv.proto.raft.RequestVoteRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fromId_ = fromId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.toId_ = toId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.term_ = term_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lastLogIndex_ = lastLogIndex_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.lastLogTerm_ = lastLogTerm_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.tinykv.proto.raft.RequestVoteRequest) {
        return mergeFrom((io.tinykv.proto.raft.RequestVoteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.tinykv.proto.raft.RequestVoteRequest other) {
      if (other == io.tinykv.proto.raft.RequestVoteRequest.getDefaultInstance()) return this;
      if (other.getFromId() != 0) {
        setFromId(other.getFromId());
      }
      if (other.getToId() != 0) {
        setToId(other.getToId());
      }
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (other.getLastLogIndex() != 0L) {
        setLastLogIndex(other.getLastLogIndex());
      }
      if (other.getLastLogTerm() != 0L) {
        setLastLogTerm(other.getLastLogTerm());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              fromId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              toId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              term_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              lastLogIndex_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              lastLogTerm_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int fromId_ ;
    /**
     * <code>int32 from_id = 1;</code>
     * @return The fromId.
     */
    @java.lang.Override
    public int getFromId() {
      return fromId_;
    }
    /**
     * <code>int32 from_id = 1;</code>
     * @param value The fromId to set.
     * @return This builder for chaining.
     */
    public Builder setFromId(int value) {

      fromId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 from_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fromId_ = 0;
      onChanged();
      return this;
    }

    private int toId_ ;
    /**
     * <code>int32 to_id = 2;</code>
     * @return The toId.
     */
    @java.lang.Override
    public int getToId() {
      return toId_;
    }
    /**
     * <code>int32 to_id = 2;</code>
     * @param value The toId to set.
     * @return This builder for chaining.
     */
    public Builder setToId(int value) {

      toId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 to_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearToId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      toId_ = 0;
      onChanged();
      return this;
    }

    private long term_ ;
    /**
     * <code>int64 term = 3;</code>
     * @return The term.
     */
    @java.lang.Override
    public long getTerm() {
      return term_;
    }
    /**
     * <code>int64 term = 3;</code>
     * @param value The term to set.
     * @return This builder for chaining.
     */
    public Builder setTerm(long value) {

      term_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 term = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTerm() {
      bitField0_ = (bitField0_ & ~0x00000004);
      term_ = 0L;
      onChanged();
      return this;
    }

    private long lastLogIndex_ ;
    /**
     * <code>int64 last_log_index = 4;</code>
     * @return The lastLogIndex.
     */
    @java.lang.Override
    public long getLastLogIndex() {
      return lastLogIndex_;
    }
    /**
     * <code>int64 last_log_index = 4;</code>
     * @param value The lastLogIndex to set.
     * @return This builder for chaining.
     */
    public Builder setLastLogIndex(long value) {

      lastLogIndex_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_log_index = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastLogIndex() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lastLogIndex_ = 0L;
      onChanged();
      return this;
    }

    private long lastLogTerm_ ;
    /**
     * <code>int64 last_log_term = 5;</code>
     * @return The lastLogTerm.
     */
    @java.lang.Override
    public long getLastLogTerm() {
      return lastLogTerm_;
    }
    /**
     * <code>int64 last_log_term = 5;</code>
     * @param value The lastLogTerm to set.
     * @return This builder for chaining.
     */
    public Builder setLastLogTerm(long value) {

      lastLogTerm_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_log_term = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastLogTerm() {
      bitField0_ = (bitField0_ & ~0x00000010);
      lastLogTerm_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tinykv.RequestVoteRequest)
  }

  // @@protoc_insertion_point(class_scope:tinykv.RequestVoteRequest)
  private static final io.tinykv.proto.raft.RequestVoteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.tinykv.proto.raft.RequestVoteRequest();
  }

  public static io.tinykv.proto.raft.RequestVoteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestVoteRequest>
      PARSER = new com.google.protobuf.AbstractParser<RequestVoteRequest>() {
    @java.lang.Override
    public RequestVoteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RequestVoteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestVoteRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.tinykv.proto.raft.RequestVoteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

